name: Setup Nix
description: Install Nix and use the magic cache
inputs:
  github_access_token:
    description: ''
    required: true
runs:
  using: composite
  steps:
    - uses: cachix/install-nix-action@08dcb3a5e62fa31e2da3d490afc4176ef55ecd72 # v30
      with:
        github_access_token: ${{ inputs.github_access_token }}
    - uses: DeterminateSystems/magic-nix-cache-action@87b14cf437d03d37989d87f0fa5ce4f5dc1a330b # v8
